runtime: custom
env: flex
resources:
    memory_gb: 1.0
    disk_size_gb: 30
automatic_scaling:
    min_num_instances: 1
    max_num_instances: 2
    cpu_utilization:
        target_utilization: 0.8
env_variables:
    DEBUG: ''
    ENVIRONMENT: production
    BOTO_CONFIG: /app/.boto
    SECRET_KEY: DtWd%M$etFfQu%CQQN9Lf*R5&$3g#wO!bPQLSs8ia&Ixkyai!0
    SECURE_SSL_REDIRECT: ''
readiness_check:
    app_start_timeout_sec: 1800
