version: '3'

services:
    web:
        image: ludoj-server:latest
        container_name: ludoj
        build:
            context: '.'
            dockerfile: Dockerfile
        environment:
            - DEBUG=
            - PORT=8000
        ports:
            - '8000:8000'
        restart: always
        networks:
            - ludoj

networks:
    ludoj:
        driver: bridge
