version: '3'

services:
    web:
        image: rg-server:latest
        container_name: rg
        build:
            context: '.'
            dockerfile: Dockerfile
        environment:
            - DEBUG=
            - PORT=8080
            - BOTO_CONFIG=/app/.boto
        ports:
            - '8080:8080'
        volumes:
            - ./data:/app/data
        restart: always
        networks:
            - rg

networks:
    rg:
        driver: bridge
