version: '3.7'

services:
    web:
        image: rg-server:latest
        container_name: rg
        environment:
            - DEBUG=
            - PORT=8080
            - BOTO_CONFIG=/app/.boto
        ports:
            - '8080:8080'
        volumes:
            - ./data:/app/data
        restart: always

    users:
        image: registry.gitlab.com/recommend.games/board-game-scraper:2.11.0
        container_name: rg-users
        command: ['python', '-m', 'board_game_scraper.pubsub_pull', '--out-path', 'gs://recommended-ludoj-logs/{time}.{number:04d}.csv', '--sleep', '3600']
        env_file: .env
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /app/gs.json
        volumes:
            - ./gs.json:/app/gs.json
        restart: always
        stop_grace_period: 15m
        stop_signal: SIGINT
