version: '3'

services:
    web:
        image: ludoj-server:latest
        container_name: ludoj
        build:
            context: '.'
            dockerfile: Dockerfile
        environment:
            - DEBUG=
            - PORT=8080
        ports:
            - '8080:8080'
        volumes:
            - ./data:/app/data
        restart: always
        networks:
            - ludoj

networks:
    ludoj:
        driver: bridge
