version: '3'

services:
    web:
        image: ludoj-server:latest
        container_name: ludoj
        build:
            context: '.'
            dockerfile: Dockerfile
        # depends_on:
        #     - db
        environment:
            - DEBUG=true
            - PORT=8000
        ports:
            - '8000:8000'
        # volumes:
        #     - ./output:/root/output
        restart: always
        networks:
            - ludoj

networks:
    ludoj:
        driver: bridge
