application: ludoj-games
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: server.wsgi.application
  login: admin
  secure: always

- url: /_ah/internalupload.*
  script: server.wsgi.application
  secure: always

- url: /static
  static_dir: static/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: server.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: server.wsgi.application
  secure: always

libraries:
- name: django
  version: '1.11'
- name: pytz
  version: '2016.4'
- name: ssl
  version: '2.7.11'

skip_files:
  - ^manage\.py$
  - ^README\.md$
  - ^install_deps$
  - ^requirements/.*\.txt$
  - ^sitepackages/dev.*
  - ^.*\.(egg|dist)-info/.*$

  # Defaults.
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$

